services:
  spark-master:
    image: apache/spark:3.5.6
    container_name: spark-master
    command: ["/opt/spark/sbin/start-master.sh"]
    environment:
      - SPARK_NO_DAEMONIZE=true
    ports:
      - "7077:7077"
      - "8080:8080"
    networks:
      - sparknet

  spark-worker:
    image: apache/spark:3.5.6
    container_name: spark-worker
    depends_on:
      - spark-master
    command: ["/opt/spark/sbin/start-worker.sh", "spark://spark-master:7077"]
    environment:
      - SPARK_NO_DAEMONIZE=true
    ports:
      - "8081:8081"
    networks:
      - sparknet

  backend:
    build: ./backend
    container_name: backend
    environment:
      - API_URL=${API_URL:-http://finnhub-client:8001/quote}
      - INFLUXDB_URL=${INFLUXDB_URL:-http://influxdb:8086}
      - INFLUXDB_TOKEN=${INFLUXDB_ADMIN_TOKEN:-local-token}
      - INFLUXDB_ORG=${INFLUXDB_ORG:-trading}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET:-market_data}
    ports:
      - "4000:4000"
    networks:
      - sparknet
      - stock_api

  frontend:
    build: ./frontend
    container_name: frontend
    environment:
      - BACKEND_URL=${BACKEND_URL:-http://localhost:4000}
    ports:
      - "8800:8800"
    networks:
      - stock_api
    volumes:
      - ./frontend:/app:Z

  finnhub-client:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: finnhub-client
    environment:
      - FINNHUB_API_KEY=${FINNHUB_API_KEY}
      - STOCK_SYMBOL=${STOCK_SYMBOL:-NVDA}
    ports:
      - "8001:8001"
    networks:
      - stock_api
    restart: unless-stopped

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME:-admin}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD:-password}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG:-trading}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET:-market_data}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN:-local-token}
    volumes:
      - influxdb_data:/var/lib/influxdb2
    ports:
      - "8086:8086"
    networks:
      - stock_api
    restart: unless-stopped

networks:
  sparknet:
  stock_api:

volumes:
  influxdb_data: