services:
  spark-master:
    image: apache/spark:3.5.6
    container_name: spark-master
    command: ["/opt/spark/sbin/start-master.sh"]
    environment:
      - SPARK_NO_DAEMONIZE=true
    ports:
      - "7077:7077"
      - "8080:8080"
    networks:
      - sparknet

  spark-worker:
    image: apache/spark:3.5.6
    container_name: spark-worker
    depends_on:
      - spark-master
    command: ["/opt/spark/sbin/start-worker.sh", "spark://spark-master:7077"]
    environment:
      - SPARK_NO_DAEMONIZE=true
    ports:
      - "8081:8081"
    networks:
      - sparknet

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8800:8800"

  finnhub-client:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: finnhub-client
    environment:
      - FINNHUB_API_KEY=${FINNHUB_API_KEY}
    command: ["${STOCK_SYMBOL:-NVDA}"]
    networks:
      - stock_api
    restart: unless-stopped

networks:
  sparknet:
  stock_api:
